### PR TITLE
Task 2 (Clustering Model)

### PR DESCRIPTION
**Pull request by jarvis-create**
The first 2 clustering models are just background runs and can be ignored.
The main clustering model is the focus. 
P.S: the eda notebook is here since I did most of the preprocessing there.

### CODE REVIEW

**Comment by Dampolo03** [comment]
Good work. Seen the main clustering model you just committed. Can you call both the PIs and PBs? Can we see some of the studios that eventually fall under each? So we verify some major film studios do not fall under the PI and vice versa.

**Comment by Sillians** [comment]
> The first 2 clustering models are just background runs and can be ignored.
> The main clustering model is the focus.
> P.S: the eda notebook is here since I did most of the preprocessing there.

@jarvis-create Nice Clustering approach, Nice work. Will have to run the Notebook myself and proffer on how it can be improved on.

**Comment by jarvis-create** [comment]
> > The first 2 clustering models are just background runs and can be ignored.
> > The main clustering model is the focus.
> > P.S: the eda notebook is here since I did most of the preprocessing there.
> 
> @jarvis-create Nice Clustering approach, Nice work. Will have to run the Notebook myself and proffer on how it can be improved on.

Yeah that'll be great.Thanks.

**Comment by gogzicole** [comment]
cool job @jarvis-create,  really cool job, but i would suggest u tried a non-linear kernel if its possible, that way you could get a better divide among the clusters, as some of the points are overlapping with each other.

**Comment by jarvis-create** [comment]
> Good work. Seen the main clustering model you just committed. Can you call both the PIs and PBs? Can we see some of the studios that eventually fall under each? So we verify some major film studios do not fall under the PI and vice versa.
 
some of them actually do.

**Comment by jarvis-create** [comment]
> cool job @jarvis-create, really cool job, but i would suggest u tried a non-linear kernel if its possible, that way you could get a better divide among the clusters, as some of the points are overlapping with each other.

I just tried different kernels including RBF and they still overlap. Seems like there's more going on to it.

**Comment by Shivam29rathore** [comment]
Really cool stuff , this notebook is self explanatory , only thing you can try is Kernel K means clustering as discussed , It can give better results in understanding the clear picture of the major movie houses and the independent ones.

**Review by gauravjain2 — APPROVED** [review]
Deep Embedded Clustering Algorithm produced two separately visible clusters.
These clusters could be attached along with the results of #18 of @Dampolo03 for final submission.

**Comment by Dampolo03** [comment]
> 
> 
> Deep Embedded Clustering Algorithm produced two separately visible clusters.
> These clusters could be attached along with the results of #23 of @Dampolo03 for final submission.

@gauravjain2 #23 is something different. Kindly check.

**Comment by gauravjain2** [comment]
> > 
> > 
> > Deep Embedded Clustering Algorithm produced two separately visible clusters.
> > These clusters could be attached along with the results of #23 of @Dampolo03 for final submission.
> 
> @gauravjain2 #23 is something different. Kindly check.

Thanks for mentioning. Edited the same.
Its #18

**Pull request merged**
