### PR TITLE
Clustering Analysis

### PR DESCRIPTION
**Pull request by Dampolo03**
First step for task two.

### CODE REVIEW

**Comment by Shivam29rathore** [comment]
It seems good , all the assumptions that I thought seems that some of these are correct in the EDA part for this task , moving in right direction.

**Comment by jarvis-create** [comment]
I think this is a very good analysis, the divide was well presented in addition it will really help sort out the clustering segments. But could you add the Walt Disney movie studio to the five major ones you already did, since there are actually six major movie studios.

**Review by VeneratioVitae — COMMENTED** [review]
Well done @Dampolo03 I think your first commit was spot on... I'm not too sure about the second one... I'm trying to do it on my end but I can't seem to format the dataset well. 
In the production companies for the movies, some companies appear singly for some movies, while for some other movies, companies collaborated with others. I feel we have to format those with multiple companies such that individual companies in the multiples are brought out.

**Comment by Dampolo03** [comment]
> 
> 
> It seems good , all the assumptions that I thought seems that some of these are correct in the EDA part for this task , moving in right direction.

Thanks for the feedback, Shivam.

**Comment by Dampolo03** [comment]
> 
> 
> I think this is a very good analysis, the divide was well presented in addition it will really help sort out the clustering segments. But could you add the Walt Disney movie studio to the five major ones you already did, since there are actually six major movie studios.

@jarvis-create Alright. Will try to look into it. Will probably do six for each then.

**Comment by Dampolo03** [comment]
> 
> 
> Well done @Dampolo03 I think your first commit was spot on... I'm not too sure about the second one... I'm trying to do it on my end but I can't seem to format the dataset well.
> In the production companies for the movies, some companies appear singly for some movies, while for some other movies, companies collaborated with others. I feel we have to format those with multiple companies such that individual companies in the multiples are brought out.

@VeneratioVitae Thanks for the feedback. Well, for the second one, I tried to perform some tasks;
- Obtain two clusters (big film studios and independents) for the whole numerical dataset.
- Obtain clusters between two columns after obtaining their respective centroids.
- Manually made two clusters (for the big film studios and independents) and obtained respective graphs between two columns.

**Comment by gogzicole** [comment]
cool job @Dampolo03 your cluster model looks really good, but just a few suggestion to get a better divide between clusters;
1. Try increasing the amount of clusters so you can have more clusters closer to each centroid with less inertia.
2. Maybe using a non linear kernel in the k-means cluster would do a better job in dividing the clusters as we have some clusters overlapping into the cluster space of another cluster. Using a non linear kernel might help reduce the silhouette  and could well do the magic.

on a general note its a very impressive work you did with the notebook 1 and 2.

**Comment by Dampolo03** [comment]
> 
> 
> cool job @Dampolo03 your cluster model looks really good, but just a few suggestion to get a better divide between clusters;
> 
>     1. Try increasing the amount of clusters so you can have more clusters closer to each centroid with less inertia.
> 
>     2. Maybe using a non linear kernel in the k-means cluster would do a better job in dividing the clusters as we have some clusters overlapping into the cluster space of another cluster. Using a non linear kernel might help reduce the silhouette  and could well do the magic.
> 
> 
> on a general note its a very impressive work you did with the notebook 1 and 2.

Acknowledged. Thanks for the feedback.

Tried the Kernel Kmeans, didn't really obtain something different. Also, after increasing the number of clusters, can you clarify how I can eventually check the divide between the independents and major film studios among the number of clusters (>2), it has been my point of concern. Expecting your response, ready to get back to work!

**Comment by teewrites** [comment]
Well done @Dampolo03 . This is good stuff. It's the description for me - insightful!

**Review by gauravjain2 — APPROVED** [review]

**Pull request merged**
