### PR TITLE
Pre-processing / EDA notebook

### PR DESCRIPTION
**Pull request by jarvis-create**
Still working on more visualizations and probable edits.

### CODE REVIEW

**Comment by quadri-olamilekan** [comment]
nice, but I don't think overview should be considered  redundant column , it should be useful

**Comment by gogzicole** [comment]
Good job on your EDA but i'm curious why did u select the first genre in the genre category for every movie as the default genre? each movie has about 2-3  genres associated with it, so why did u select the first element in that list as your default genre?

**Comment by jarvis-create** [comment]
> Good job on your EDA but i'm curious why did u select the first genre in the genre category for every movie as the default genre? each movie has about 2-3 genres associated  with it, so why did u select the first element in that list as your default genre?

That particular sample in the notebook only had one genre, there was no deliberate attempt to pick the first one, it was only in crew and cast I did special selecting.

**Comment by jarvis-create** [comment]
> nice, but I don't think overview should be considered redundant column , it should be useful

Yeah, it certainly could be now that I think about it. Thanks.

**Pull request merged**
