### PR TITLE
Exploratory data analysis an visualization.

### LINKED ISSUE #1: EDA
Exploratory Data Analysis

### PR DESCRIPTION
**Pull request by Manuelkila**
Kindly go through. Give suggestions, clarifications, and improvements.

### CODE REVIEW

**Comment by quadri-olamilekan** [comment]
nice visualizations

**Comment by gissaonilu** [comment]
Nice Visualizations

**Comment by chimatic** [comment]
Good work

**Comment by Dampolo03** [comment]
Brilliant work done.

**Comment by gogzicole** [comment]
Really good work kila, but can you decompose some of the plots? try plotting some of them on separate cells, because the text labels are too small and very hard to see or know what a plot is trying to show.

**Comment by Manuelkila** [comment]
Oh..thanks. I thought of that, too. My idea is to make them see the all correlations and distributions at a glance. That way, you can get the big picture without going back and forth. I will modify the labels to make them bigger and clearer. I hope that will solve the issue.

**Comment by Shivam29rathore** [comment]
Really cool stuff , this notebook is self explanatory , only thing you can try is Kernel K means clustering as discussed , It can give better results in understanding the clear picture of the major movie houses and the independent ones.

**Comment by Manuelkila** [comment]
Shivsm, this is the EDA task. The clustering is task 2 and it has been assigned to someone else.

**Comment by Shivam29rathore** [comment]
This notebook is self explanatory and actually is quite Descriptive , It justifies the idea of EDA and is good to for the production.

**Review by gauravjain2 — APPROVED** [review]
Nice Work for EDA

**Pull request merged**
